name: Daily Arxiv Paper Report

on:
  schedule:
    # Run at 8:00 UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate daily report
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
        EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
      run: python scripts/run_daily_report.py
      
    - name: Upload report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: arxiv-report
        path: reports/
        retention-days: 30